server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location /api/ {
        proxy_pass http://host.docker.internal:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = / {
        try_files /home/index.html =404;
    }

    location = /auth {
        try_files /auth/index.html =404;
    }

    location = /me {
        try_files /me/index.html =404;
    }
    location = /superuser {
    try_files /superuser/index.html =404;
    }
    location = /admin {
    try_files /admin/index.html =404;
    }

    location ~ ^/room/[0-9]+$ {
        try_files /room/index.html =404;
    }

    location /home/ {
        try_files $uri =404;
    }

    location /auth/ {
        try_files $uri =404;
    }

    location /room/ {
        try_files $uri =404;
    }

    location /me/ {
        try_files $uri =404;
    }
    location /superuser/ {
    try_files $uri =404;
    }
    location /admin/ {
    try_files $uri =404;
    }

    location /shared/ {
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}